"""empty message

Revision ID: d8e852d4f3dd
Revises: 9f945d8ae31c
Create Date: 2025-04-12 16:34:52.540962

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8e852d4f3dd'
down_revision = '9f945d8ae31c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('user_username_key', type_='unique')
        batch_op.drop_column('username')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.create_unique_constraint('user_username_key', ['username'])

    # ### end Alembic commands ###
